function slurm_write_bash( numJobs, jobDir )
%slurm_write_bash Writes bash script to initiate batch job

scriptText = [...
'#!/bin/bash\n',...
'#SBATCH --time 24:00:00\n',...
'#SBATCH --array=0-%i\n',...
'\n',...
'module load matlab\n',...
'index=$( printf ''%%i'' ${SLURM_ARRAY_TASK_ID} )\n',...
'matlab -nodisplay -nodesktop -nosplash -r',...
' "addpath(''../CHESS-Research/MATLAB'');',...
'slurm_batch_wrapper(''$index''); exit"\n',...
];

fileID = fopen(fullfile(jobDir,'array_batch_script.sh'),'w');
fprintf(fileID,scriptText,numJobs);
fclose(fileID);

end

