function slurm_write_matlab( numJobs, jobDir, matlabFuncName, scriptFileName, jobDirName )
%slurm_write_bash Writes bash script to initiate batch job

scriptText = [...
'#!/bin/bash\n',...
'#SBATCH --time 48:00:00\n',...
'#SBATCH --mem-per-cpu=4000\n',...
'#SBATCH -p mpi\n',...
'#SBATCH -c 64\n',...
'#SBATCH --error=slurm_error.err\n',...
'#SBATCH --mail-type=END\n',...
'#SBATCH --mail-user=dbanco02@tufts.edu\n',...
'\n',...
'module load matlab\n',...
'matlab -nodisplay -nodesktop -nosplash -r',...
' "addpath(''../CHESS-Research/MATLAB'');',...
matlabFuncName, '(%i,',jobDirName,'); exit"\n',...
];

fileID = fopen(fullfile(jobDir,scriptFileName),'w');
fprintf(fileID,scriptText,numJobs);
fclose(fileID);

end

