#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 24 20:37:21 2024

@author: dbanco
"""
import os
import pickle

k = 2054
topPath = "/mnt/scratch/dbanco/c103_processing/Sample-3/"
read_path = os.path.join(topPath,'outputs')

with open(os.path.join(read_path,f'trackData_{k}.pkl'), 'rb') as f:
    track = pickle.load(f)